MNT: Re-rendered with conda-smithy 3.2.2 and pinning 2018.12.18

diff --git a/.travis.yml b/.travis.yml
--- a/.travis.yml
+++ b/.travis.yml
@@ -4,38 +4,62 @@
 language: generic
 
 os: osx
-osx_image: beta-xcode6.1
+osx_image: xcode9.4
+
 
 env:
   matrix:
-    
-    - CONDA_PY=34
-    - CONDA_PY=35
+    - CONFIG=osx_python3.6
+    - CONFIG=osx_python3.7
+
   global:
     # The BINSTAR_TOKEN secure variable. This is defined canonically in conda-forge.yml.
     - secure: "A8unywkX1tjMfHyD1TuRBiGlixual4Pf9wAiu7cyoyF3f5kV1zp9UCceU8Ea+w/KgxaKmfUKND8AljWkTEicsfsKlWmcthH5A3yKhsaWk0SklHp6QguopJnOLJn/nuVJKtFVnjC+yJQIbqa8mK66wtJ7O27jd+T1gJimjWXITUxd+LOF4AI6nOJUHkq8E+9YRLDw0KzqGHN6jBXM50Sx1s30CINxDORHF+cJeJU9OcusCNga5Dltct3vnxjmdflePmJBVwq3XQeh4kdjiDleicmdLZAxlMwRyJ0nydzXNMPhtHfHb7tQmSkCiaq7qjShp999iHd/LIaF45LEdCzDhay34TSJa1F+YRg6/miChZy7fMbUwd1maFg+lo8+mTYNJPW/nfpXk6O8aYU4eggJrDLLh0lhXMaYcF20hz/LwIMx6BBW9HLiFWOMmPxCXp7bNkWccBNyT6i+1vxFqUogG4Oa7VeFFLvPIzKowmO2LMauPJq8v5bwvu49Xxi+GpXbMkSuP0ovCsIrmbTg8fJ+tNAvGpnY6vRgN7o6DyRF8s+CF+oHVu1gJg9rhQJNrqUNvKZkSibP7/sr/YqNN2TCQAoBjdqTQ24AWa9u/JF13ctyVDQrKcW7pEhvZzt0HfWpYdwdUbIqZK5Fv6ioSGjELLflolI3yOt3BYB2q+heesc="
 
 
 before_install:
+    # Fast finish the PR.
+    - |
+      (curl https://raw.githubusercontent.com/conda-forge/conda-forge-ci-setup-feedstock/branch2.0/recipe/conda_forge_ci_setup/ff_ci_pr_build.py | \
+          python - -v --ci "travis" "${TRAVIS_REPO_SLUG}" "${TRAVIS_BUILD_NUMBER}" "${TRAVIS_PULL_REQUEST}") || exit 1
+
     # Remove homebrew.
-    - brew remove --force $(brew list)
-    - brew cleanup -s
-    - rm -rf $(brew --cache)
+    - |
+      echo ""
+      echo "Removing homebrew from Travis CI to avoid conflicts."
+      curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/uninstall > ~/uninstall_homebrew
+      chmod +x ~/uninstall_homebrew
+      ~/uninstall_homebrew -fq
+      rm ~/uninstall_homebrew
+
 
 install:
+    # Install Miniconda.
     - |
+      echo ""
+      echo "Installing a fresh version of Miniconda."
       MINICONDA_URL="https://repo.continuum.io/miniconda"
       MINICONDA_FILE="Miniconda3-latest-MacOSX-x86_64.sh"
       curl -L -O "${MINICONDA_URL}/${MINICONDA_FILE}"
       bash $MINICONDA_FILE -b
 
+    # Configure conda.
+    - |
+      echo ""
+      echo "Configuring conda."
       source /Users/travis/miniconda3/bin/activate root
-      conda config --add channels conda-forge
-      conda config --set show_channel_urls true
-      conda install --yes --quiet conda-forge-build-setup
+
+      conda install -n root -c conda-forge --quiet --yes conda-forge-ci-setup=2
+      setup_conda_rc ./ ./recipe ./.ci_support/${CONFIG}.yaml
+
       source run_conda_forge_build_setup
 
-script:
-  - conda build ./recipe
+    # compiler cleanup
+    - |
+      mangle_compiler ./ ./recipe ./.ci_support/${CONFIG}.yaml
 
-  - upload_or_check_non_existence ./recipe conda-forge --channel=main
+script:
+  # generate the build number clobber
+  - make_build_number ./ ./recipe ./.ci_support/${CONFIG}.yaml
+  - conda build ./recipe -m ./.ci_support/${CONFIG}.yaml --clobber-file ./.ci_support/clobber_${CONFIG}.yaml
+  - upload_package ./ ./recipe ./.ci_support/${CONFIG}.yaml
